// Plain-Node test over the raw snippets/kai.json content (no VS Code API
// needed - this is just JSON + string checks): confirms the beginner
// `let`/`mut` snippets use CURRENT valid KAI syntax and that `let mut`
// (invalid - `mut` is its own binding keyword, never combined with
// `let`) is never generated by any snippet body.

import * as assert from 'assert';
import * as fs from 'fs';
import * as path from 'path';

interface Snippet {
    prefix: string;
    body: string | string[];
    description?: string;
}

function loadSnippets(): Record<string, Snippet> {
    const snippetsPath = path.join(__dirname, '..', '..', 'snippets', 'kai.json');
    const raw = fs.readFileSync(snippetsPath, 'utf8');
    return JSON.parse(raw) as Record<string, Snippet>;
}

function bodyText(snippet: Snippet): string {
    return Array.isArray(snippet.body) ? snippet.body.join('\n') : snippet.body;
}

function findByPrefix(snippets: Record<string, Snippet>, prefix: string): Snippet {
    const entry = Object.values(snippets).find((snippet) => snippet.prefix === prefix);
    assert.ok(entry, `expected a snippet with prefix "${prefix}"`);
    return entry as Snippet;
}

function testLetSnippetUsesCurrentSyntax(): void {
    const snippets = loadSnippets();
    const letSnippet = findByPrefix(snippets, 'let');
    const text = bodyText(letSnippet);

    assert.match(text, /^let \$\{1:name\}: \$\{2:i64\} = \$\{3:0\}$/);
    assert.ok(!text.includes('let mut'), '`let mut` is never valid KAI syntax');
}

function testMutSnippetUsesCurrentSyntax(): void {
    const snippets = loadSnippets();
    const mutSnippet = findByPrefix(snippets, 'mut');
    const text = bodyText(mutSnippet);

    assert.match(text, /^mut \$\{1:name\}: \$\{2:i64\} = \$\{3:0\}$/);
    assert.ok(!text.includes('let mut'));
}

function testNoSnippetBodyEverContainsLetMut(): void {
    const snippets = loadSnippets();
    for (const [name, snippet] of Object.entries(snippets)) {
        assert.ok(!bodyText(snippet).includes('let mut'), `snippet "${name}" must not contain "let mut"`);
    }
}

function testNoDuplicatePrintSnippet(): void {
    // print() is the CompletionItemProvider's job (completions.ts) - the
    // snippet file must not also define a `print` prefix, to avoid two
    // competing suggestions for the same thing (§11/§12).
    const snippets = loadSnippets();
    const prefixes = Object.values(snippets).map((snippet) => snippet.prefix);
    assert.ok(!prefixes.includes('print'), 'print should come from the CompletionItemProvider only, not a snippet');
}

function main(): void {
    testLetSnippetUsesCurrentSyntax();
    testMutSnippetUsesCurrentSyntax();
    testNoSnippetBodyEverContainsLetMut();
    testNoDuplicatePrintSnippet();

    console.log('snippets.test.ts: all tests passed');
}

main();
